pattern_name: activator activity

pattern_iri: http://purl.obolibrary.org/obo/go/patterns/activator_activity.yaml

description: TODO

classes:
  molecular function regulator: 'GO:0098772'
  catalytic activity: 'GO:0003824'

relations:
  positively regulates: 'RO:0002213' 
  
vars:
  regulated_activity: "'catalytic activity'" 

substitutions:
   - 
     in: regulated_activity
     out: regulated_activity_munged
     match: "(.+) activity"
     sub: '\1'  

data_list_vars:
  def_dbxrefs: "xsd:string"
  
name:
  text: "%s activator activity"
  vars:   
    - 'regulated_activity_munged'
    
def: 
  text: "Direct interaction with a gene product or complex that has %s, 
    resulting in positive regulation of its %s. Direct interaction 
    in this case includes binding and interactions leading to 
    covalent modification."
  vars:
    - 'regulated_activity'
    - 'regulated_activity'

namespace: 
  text: 'biological_process'

equivalentTo: 
  text: "'molecular function regulator' that 'positively regulates' some %s" 
  vars:
    - 'regulated_activity'
